config/routes.rb
Alexandria::Application.routes.draw do
  resources :authors

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :strikes

  resources :checkouts, except: :new

  resources :reservations

  resources :books, except: :new do
    member do
      get 'put_away'
    end
  end

  resources :users

  match 'check_in', to: 'checkouts#check_in', via: :post

  root 'root#index'
end

app/models/strike.rb
# Strike Model
class Strike < ActiveRecord::Base
  belongs_to :patron, class_name: 'User'
  belongs_to :distributor, class_name: 'User'
  belongs_to :reason

  validates :reason_id, :patron_id, :distributor_id, presence: true
  validate :is_distributor
  validate :other_has_info

  default_scope { order('id ASC') }

  def message
    string = reason.message
    string = "#{string}: #{other_info}" unless other_info.blank?
    string
  end

  def is_distributor
    unless !distributor.nil? && (distributor.distributor? || distributor.librarian?)
      errors.add(:distributor, 'is not a distributor or librarian.')
    end
  end

  def other_has_info
    if reason == Reason.find_by_message('Other') && other_info.blank?
      errors.add(:strike, 'needs more information if "Other" is chosen for reason.')
    end
  end
end

app/controllers/strikes_controller.rb
# Strikes controller
class StrikesController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_action :set_strike, only: [:show, :edit, :update, :destroy]

  # GET /strikes
  # GET /strikes.json
  def index
    @strikes = Strike.all
  end

  # GET /strikes/1
  # GET /strikes/1.json
  def show
  end

  # GET /strikes/new
  def new
    @strike = Strike.new
  end

  # GET /strikes/1/edit
  def edit
  end

  # POST /strikes
  # POST /strikes.json
  def create
    @strike = Strike.new(strike_params)
    User.all.each do |user|
      @strike.distributor = user if user.barcode == params['distributor_barcode']
      break unless @strike.distributor.nil?
    end
    respond_to do |format|
      if @strike.save
        StrikeMailer.strike(@strike).deliver
        if @strike.patron.active_strikes.count == Rails.configuration.strikes_for_ban
          StrikeMailer.banned(@strike.patron).deliver
          patron = @strike.patron
          patron.banned = true
          patron.save
        end
        format.html { redirect_to @strike, notice: 'Strike was successfully created.' }
        format.json { render 'show', status: :created, location: @strike }
      else
        format.html { render 'new' }
        format.json { render json: @strike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strikes/1
  # PATCH/PUT /strikes/1.json
  def update
    respond_to do |format|
      if @strike.update(strike_params)
        format.html { redirect_to @strike, notice: 'Strike was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @strike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strikes/1
  # DELETE /strikes/1.json
  def destroy
    @strike.destroy
    respond_to do |format|
      format.html { redirect_to strikes_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_strike
    @strike = Strike.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def strike_params
    params.require(:strike).permit(:other_info, :reason_id, :patron_id, :active)
  end
end

app/views/strikes/_form.html.haml
.well.well-small
  = form_for strike do |f|
    -if strike.errors.any?
      #error_explanation
        %h2= "#{pluralize(strike.errors.count, "error")} prohibited this strike from being saved:"
        %ul
          - strike.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :patron
      = f.select :patron_id, options_for_select(User.all.collect { |u| [u.user_name, u.id] }, strike.patron.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :distributor_barcode
      = f.password_field :distributor_id, name: 'distributor_barcode', class: 'form-control'
    .form-group
      = f.label :reason
      = f.select :reason_id, options_for_select(Reason.all.collect { |r| [r.message, r.id] }, strike.reason.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :other_info
      = f.text_field :other_info, class: 'form-control'
    .form-group
      = f.label :active
      = f.check_box :active
    .actions
      = f.submit 'Save', class: 'btn btn-primary'

app/views/strikes/edit.html.haml
%h1 Editing strike

= render 'form', strike: @strike

app/views/strikes/index.html.haml
%h3 Listing strikes

%table.table.table-striped.table-hover
  %tr
    %th Patron
    %th Distributor
    %th Reason
    %th Other Info
    %th
    %th

  - @strikes.each do |strike|
    %tr{onclick: "location.href='#{strike_path(strike)}'"}
      %td= strike.patron.user_name
      %td= strike.distributor.user_name
      %td= strike.reason.message
      %td= strike.other_info
      %td= link_to 'Edit', edit_strike_path(strike)
      %td= link_to 'Destroy', strike, data: { confirm: 'Are you sure?'}, method: :delete
%br

app/views/strikes/new.html.haml
%h1 New strike

= render 'form', strike: @strike

app/views/strikes/show.html.haml
.page-header
  %h2 Strike

%dl.dl-horizontal
  %dt Patron:
  %dd= @strike.patron.user_name
  %dt Distributor:
  %dd= @strike.distributor.user_name
  %dt Message:
  %dd= @strike.message
  %dt Recieved On:
  %dd= @strike.created_at.strftime('%B %d, %Y')
  %dt Active
  %dd= @strike.active ? 'Yes' : 'No'