config/routes.rb
Alexandria::Application.routes.draw do
  resources :authors

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :strikes

  resources :checkouts, except: :new

  resources :reservations

  resources :books, except: :new do
    member do
      get 'put_away'
    end
  end

  resources :users

  match 'check_in', to: 'checkouts#check_in', via: :post

  root 'root#index'
end

app/models/author.rb
require 'people'

# Author model class
class Author < ActiveRecord::Base
  PARSER = People::NameParser.new

  after_initialize :default_values
  # Unique author validator class
  class UniqueAuthorValidator < ActiveModel::Validator
    def validate(record)
      other_authors = Author.where(first_name: record.first_name,
                                   middle_initial: record.middle_initial,
                                   last_name: record.last_name)
      other_authors.delete_if { |x| x.id == record.id }
      if other_authors.size != 0
        record.errors[:base] << 'This author already exists in the system'
      end
    end
  end

  has_many :author_books
  has_many :books, through: :author_books

  validates :middle_initial, length: { maximum: 1 }
  validates_with UniqueAuthorValidator

  def default_values
    self.middle_initial ||= ''
  end

  ##
  # Creates an Author when given a single string name. It DOES NOT save it.
  #
  # It parses the name, expecting it to be space deliniated into 3 parts.
  # It expects strings in the format "<first> <last>" or "<first> <middle> <last>"
  def self.create_with_name(name)
    new(parse_name(name))
  end

  ##
  # Finds an Author when given a single string name.
  #
  # It parses the name, expecting it to be space deliniated into 3 parts.
  # It expects strings in the format "<first> <last>" or "<first> <middle> <last>"
  def self.find_with_name(name)
    name = parse_name(name)

    Author.where(first_name:   name[:first_name],
                 middle_initial: name[:middle_initial],
                 last_name:   name[:last_name])[0]
  end

  ##
  # Finds an author with the given name. If there is no such author,
  # creates one and returns that. If created, it DOES save it.
  #
  # Uses the parsing rules: "<first> <last>" or "<first> <middle> <last>"
  def self.find_or_create(name)
    author = find_with_name(name)
    if author.nil?
      author = create_with_name(name)
      author.save
    end

    author
  end

  ##
  # Parses the names into expected portions. All methods that parse
  # a name for Author use this.
  def self.parse_name(name)
    parsed_name = PARSER.parse name

    {
      first_name:     parsed_name[:first],
      middle_initial: parsed_name[:middle][0] || '',
      last_name:      parsed_name[:last]
    }
  end

  def full_name
    "#{first_name} #{middle_initial} #{last_name}"
  end
end

app/controllers/authors_controller.rb
# Controller for the authors
class AuthorsController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render 'show', status: :created, location: @author }
      else
        format.html { render 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:first_name, :last_name, :middle_initial)
  end
end

app/views/authors/_form.html.haml
.well.well-small
  = form_for author do |f|
    - if author.errors.any?
      #error_explanation
        %h2= "#{pluralize(author.errors.count, "error")} prohibited this author from being saved:"
        %ul
          - author.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: 'form-control'
    .form-group
      = f.label :middle_initial
      = f.text_field :middle_initial, class: 'form-control'
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to 'Back', back_path, class: 'btn btn-default'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form', author: @author, back_path: author_path(@author)

app/views/authors/index.html.haml
%h1 Listing authors

%table.table.table-striped.table-responsive
  %tr
    %th First name
    %th Middle initial
    %th Last name
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.first_name
      %td= author.middle_initial
      %td= author.last_name
      %td= link_to 'Show', author, class: 'btn btn-default'
      %td= link_to 'Edit', edit_author_path(author), class: 'btn btn-default'
      %td= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form', author: @author, back_path: authors_path

app/views/authors/show.html.haml
%h1
	= @author.full_name

- @author.books.each do |book|
	= render "books/book", book: book