config/routes.rb
Alexandria::Application.routes.draw do
  resources :authors

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :strikes

  resources :checkouts, except: :new

  resources :reservations

  resources :books, except: :new do
    member do
      get 'put_away'
    end
  end

  resources :users

  match 'check_in', to: 'checkouts#check_in', via: :post

  root 'root#index'
end

app/models/user.rb
require 'bcrypt'
# User model
class User < ActiveRecord::Base
  include BCrypt
  # Only permit omniauth accounts
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  devise :database_authenticatable

  has_many :reservations
  has_many :books_reserved, through: :reservations, source: :book
  has_many :checkouts, foreign_key: :patron_id
  has_many :books_checked_out, through: :checkouts, source: :book
  has_many :strikes, foreign_key: :patron_id
  belongs_to :role

  after_initialize :default_values

  default_scope { order('id ASC') }

  def barcode
    @barcode ||= Password.new(barcode_hash) unless barcode_hash.nil?
  end

  def barcode=(new_barcode)
    @barcode = Password.create(new_barcode)
    self.barcode_hash = @barcode
  end

  def default_values
    self.role ||= Role.find_by_name('patron')
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource = nil)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(user_name: data['name'],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20]
          )
    end
    user
  end

  def active_strikes
    strikes.where(active: true)
  end

  def inactive_strikes
    strikes.where(active: false)
  end

  def active_checkouts
    checkouts.select{ |x| x.checked_in_at.nil? }
  end

  def inactive_checkouts
    checkouts.select{ |x| x.checked_in_at.present? }
  end

  def active_reservations
    reservations.select{ |x| !x.fulfilled and !x.expired? }
  end

  def inactive_reservations
    reservations.select{ |x| x.fulfilled or x.expired? }
  end

  def librarian?
    role.try(:name) == 'librarian'
  end

  def distributor?
    role.try(:name) == 'distributor'
  end

  def patron?
    role.try(:name) == 'patron'
  end

  def technical_admin?
    role.try(:name) == 'technical admin'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# Ominauth Callbacks Controller
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_google_oauth2(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
# Users controller
class UsersController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.barcode = params[:barcode] if params[:barcode]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render 'show', status: :created, location: @user }
      else
        format.html { render 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      @user.barcode = params[:barcode] unless params[:barcode].blank?
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :banned, :role_id, :user_name)
  end
end

app/views/users/_display_books.html.haml
- list.each_slice(4) do |items|
  .row
    - items.each do |item|
      .col-md-3
        .text-center
          %br
          - if item.book.google_book_data.img_small.present?
            = link_to(image_tag(item.book.google_book_data.img_small), item)
          - else
            .blank-thumbnail-medium.center
  .row
    - items.each do |item|
      .col-md-3
        .text-center
          %br
          = link_to item.book.title, item

app/views/users/_form.html.haml
.well.well-small
  = form_for user do |f|
    -if user.errors.any?
      #error_explanation
        %h2= "#{pluralize(user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - user.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :user_name
      = f.text_field :user_name, class: 'form-control'
    .form-group
      = f.label :banned
      = f.check_box :banned
    .form-group
      = f.label :role
      = f.select :role_id, options_for_select(Role.all.collect { |u| [u.name, u.id] }, user.role.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :barcode
      = f.password_field :barcode, name: 'barcode', class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to 'Back', back_path, class: 'btn btn-default'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form', user: @user, back_path: @user

app/views/users/index.html.haml
%h1 Listing users

%table.table.table-striped.table-hover
  %tr
    %th User name
    %th Banned
    %th Role
    %th
    %th

  - @users.each do |user|
    %tr{onclick: "location.href='#{user_path(user)}'"}
      %td= user.user_name
      %td= user.banned
      %td= user.role.name
      %td= link_to 'Edit', edit_user_path(user), class: 'btn btn-default'
      %td= link_to 'Destroy', user, data: { confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-default'

app/views/users/new.html.haml
%h1 New user

= render 'form', user: @user, back_path: users_path

app/views/users/show.html.haml
.page-header
  %h1= @user.user_name

.row
  %dl.dl-horizontal
    %dt Role
    %dd= @user.role.name.capitalize
    %dt Strikes Recieved
    %dd= "#{@user.active_strikes.count} active/ #{@user.inactive_strikes.count} inactive"
    %dt Strikes
    - if @user.strikes.count == 0
      %dd No strikes. Good job!
    - else
      - @user.active_strikes.each do |strike|
        %dd= link_to strike.message, strike
      %i
        - @user.inactive_strikes.each do |strike|
          %dd= link_to strike.message, strike
    %dt Banned
    %dd= @user.banned ? 'Yes' : 'No'

.page-header
  %h2 Active Checkouts

= render 'display_books', list: @user.active_checkouts

.page-header
  %h2 Active Reservations

= render 'display_books', list: @user.active_reservations

.page-header
  %h2 Inactive Checkouts

= render 'display_books', list: @user.inactive_checkouts

.page-header
  %h2 Inactive Reservations

= render 'display_books', list: @user.inactive_reservations