config/routes.rb
Alexandria::Application.routes.draw do
  resources :authors

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :strikes

  resources :checkouts, except: :new

  resources :reservations

  resources :books, except: :new do
    member do
      get 'put_away'
    end
  end

  resources :users

  match 'check_in', to: 'checkouts#check_in', via: :post

  root 'root#index'
end

app/models/checkout.rb
# Checkout model
class Checkout < ActiveRecord::Base

  scope :active, ->  { where(checked_in_at: nil) }
  scope :patron, -> patron { where(patron_id: patron) }
  scope :book, -> book { where(book_id: book) }
  scope :overdue, -> { all.select{ |x| x.overdue? } }

  after_initialize :default_values

  belongs_to :patron, class_name: 'User'
  belongs_to :distributor, class_name: 'User'
  belongs_to :distributor_check_in, class_name: 'User'
  belongs_to :book

  delegate :title, to: :book
  delegate :user_name, to: :patron

  validates :checked_out_at, :distributor_id, :patron_id, :book_id, presence: true
  validate :unique_checkout, on: :create
  validate :book_not_restricted
  validate :book_not_unavailable
  validate :is_a_distributor
  validate :patron_not_banned
  validate :first_reservation, on: :create

  default_scope { order('id ASC') }

  def default_values
    self.checked_out_at ||= DateTime.now
    self.due_date ||= checked_out_at + Rails.configuration.checkout_period
  end

  def self.checked_out(book, patron)
    checkouts = Checkout.where(patron_id: patron.id, checked_in_at: nil).select do |i|
      i.book.try(:id) == book.id
    end

    !checkouts.empty?
  end

  def self.all_active
    Checkout.where(checked_in_at: nil)
  end

  def unique_checkout
    unless book.nil?
      book_checkouts = Checkout.all_active.where(book_id: book.id)
      unless book_checkouts.count < book.quantity
        errors.add(:book, 'is already checked out.')
      end
    end
  end

  def book_not_restricted
    errors.add(:book, 'is restricted can not be checked out.') if book.present? && book.restricted
  end

  def book_not_unavailable
    errors.add(:book, 'is unavailable can not be checked out.') if book.present? && book.unavailable
  end

  def is_a_distributor
    unless !distributor.nil? && (distributor.distributor? || distributor.librarian?)
      errors.add(:distributor, 'is not a distributor or librarian.')
    end
  end

  def patron_not_banned
    errors.add(:patron, 'cannot checkout a book if banned') if patron.nil? || patron.banned
  end

  def first_reservation
    res = book.reservations.select { |r| !r.fulfilled and !r.expired? }.sort! { |a, b| a.created_at <=> b.created_at }.first if book.present?
    unless res.nil? or res.user == patron
      errors.add(:someone, 'has already reserved this book.')
    end
  end

  def overdue?
    DateTime.now > self.due_date && checked_in_at.blank?
  end

  def need_reminding?
    Date.today + Rails.configuration.remind_before == self.due_date.to_date && checked_in_at.blank?
  end

  def send_overdue
    if overdue?
      self.due_date += Rails.configuration.checkout_period
      save
      strike = Strike.new
      strike.patron = patron
      strike.distributor = distributor
      strike.reason = Reason.find_by_message('Overdue book')
      strike.save
      CheckoutMailer.overdue_book(self).deliver
      if patron.strikes.count == Rails.configuration.strikes_for_ban
        StrikeMailer.banned(patron).deliver
        patron.banned = true
        patron.save
      end
    end
  end

  def send_reminder
    CheckoutMailer.reminder(self).deliver if need_reminding?
  end

  def self.send_mailers
    all.each do |checkout|
      checkout.send_overdue
      checkout.send_reminder
    end
  end
end

app/controllers/checkouts_controller.rb
# Checkouts controller
class CheckoutsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_action :set_checkout, only: [:show, :edit, :update, :destroy]
  has_scope :active, type: :boolean
  has_scope :patron
  has_scope :book
  has_scope :overdue, type: :boolean

  # GET /checkouts
  # GET /checkouts.json
  def index
    scope = apply_scopes(Checkout)
    @checkouts = scope.respond_to?(:to_a) ? scope.to_a : scope.all
    @checkouts = @checkouts.paginate(page: params['page'])
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
  end

  # GET /checkouts/1/edit
  def edit
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new
    User.all.each do |user|
      @checkout.distributor = user if user.barcode == params['distributor_barcode']
      @checkout.patron = user if user.barcode == params['patron_barcode']
      break unless @checkout.patron.nil? || @checkout.distributor.nil?
    end
    @checkout.book = Book.find_by_isbn(params['isbn']) unless params['isbn'].nil?
    respond_to do |format|
      if @checkout.save
        check_reservation
        # CheckoutMailer.checkout_book(@checkout).deliver
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render json: { title: @checkout.book.title }, status: :created, location: @checkout.book }
      else
        format.html { redirect_to root_path, notice: 'Checkout was not created.' }
        format.json { render json: @checkout.errors.as_json(full_messages: true) , status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkouts/1
  # PATCH/PUT /checkouts/1.json
  def update
    @checkout.checked_in_at = DateTime.now if params[:checkout][:checked_in_at] && params[:checkout][:checked_in_at] == 'now'
    respond_to do |format|
      if @checkout.update(checkout_params)
        if params[:checkout][:checked_in_at] == 'now'
          format.html { redirect_to put_away_book_url(@checkout.book), notice: 'Book was succesfully checked in.' }
          format.json { head :no_content }
        else
          format.html { redirect_to request.referer, notice: 'Checkout was successfully updated.' }
          format.json { head :no_content }
        end
      else
        format.html { render 'edit' }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout.destroy
    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end

  def check_in
    patron = nil
    distributor_check_in = nil
    User.all.each do |user|
      distributor_check_in = user if user.barcode == params['distributor_barcode']
      patron = user if user.barcode == params['patron_barcode']
      break unless distributor_check_in.nil? or patron.nil?
    end
    @checkout = Book.find_by_isbn(params['isbn']).try(:active_checkout, patron)
    unless @checkout.nil?
      @checkout.checked_in_at = DateTime.now
      @checkout.distributor_check_in = distributor_check_in
    end
    respond_to do |format|
      if @checkout.try(:distributor_check_in).try(:distributor?) || @checkout.try(:distributor_check_in).try(:librarian?)
        @checkout.save
        left_right = Lccable.where_to_place(@checkout.book)
        hash = {
          book: {
            title: @checkout.book.title,
            lcc: @checkout.book.lcc
          },
          left: {
            title: left_right[:left].try(:title) || '',
            image: left_right[:left].try(:google_book_data).try(:img_small) || '',
            lcc: left_right[:left].try(:lcc) || ''
          },
          right: {
            title: left_right[:right].try(:title) || '',
            image: left_right[:right].try(:google_book_data).try(:img_small) || '',
            lcc: left_right[:right].try(:lcc) || ''
          },
          shelf: {
            number: left_right[:shelf].to_s
          }
        }
        format.html { redirect_to put_away_book_url(@checkout.book), notice: 'Book was succesfully checked in.' }
        format.json { render json: hash, status: :ok, location: @checkout.book }
      else
        format.html { redirect_to check_in_url, alert: 'Book not checked out, invalid distributor, or invalid patron' }
        if @checkout.present?
          format.json { render json: @checkout.errors.as_json(full_messages: true), status: :unprocessable_entity }
        else
          format.json { render json: { checkout: ["checkout does not exist for book"]}, status: :unprocessable_entity}
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_checkout
    @checkout = Checkout.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def checkout_params
    params.require(:checkout).permit(:checked_out_at, :patron_id, :book_id, :distributor_id, :due_date)
  end

  def check_reservation
    reservation = Reservation.get_reservation(@checkout.book, @checkout.patron)
    if reservation
      reservation.fulfilled = true
      reservation.save
    end
  end
end

app/views/checkouts/_form.html.haml
.well.well-small
  = form_for checkout do |f|
    -if checkout.errors.any?
      #error_explanation
        %h2= "#{pluralize(checkout.errors.count, "error")} prohibited this checkout from being saved:"
        %ul
          - checkout.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :patron
      = f.select :patron_id, options_for_select(User.all.collect { |u| [u.user_name, u.id] }, checkout.patron.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :distributor
      = f.select :distributor, options_for_select(User.all.select{|u| u.distributor? or u.librarian? }.collect { |u| [u.user_name, u.id] }, checkout.distributor.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :book
      = f.select :book_id, options_for_select(Book.all.collect { |b| [b.title, b.id] }, checkout.book.try(:id)), { include_blank: true }, { class: 'chosen-select form-control'}
    .form-group
      = f.label :checked_out_at
      .input-group.date.datepicker
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :checked_out_at, class: 'form-control'
    .form-group
      = f.label :checked_in_at
      .input-group.date.datepicker
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :checked_in_at, class: 'form-control'
    .form-group
      = f.label :due_date
      .input-group.date.datepicker
        %span.input-group-addon
          %i.fa.fa-calendar
        = f.text_field :due_date, class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-primary'
      = link_to 'Back', back_path, class: 'btn btn-default'

app/views/checkouts/edit.html.haml
%h1 Editing checkout

= render 'form', checkout: @checkout, back_path: checkout_path(@checkout)

app/views/checkouts/index.html.haml
.btn-group.pull-right
  %button.btn.btn-default{type: 'button', onclick: "location.href='#{checkouts_path}'"}
    All Checkouts
  %button.btn.btn-default{type: 'button', onclick: "location.href='#{checkouts_path(params: {active:true})}'"}
    Active Checkouts
  %button.btn.btn-default{type: 'button', onclick: "location.href='#{checkouts_path(params: {overdue:true})}'"}
    Overdue
%h3 Checkouts
%table.table.table-striped.table-hover
  %tr
    %th id
    %th Patron
    %th Distributor Check Out
    %th Distributor Check In
    %th Book
    %th Checked Out Time
    %th Checked In Time
    %th Due Date

  - @checkouts.each do |checkout|
    %tr{onclick: "location.href='#{checkout_path(checkout)}'"}
      %td= checkout.id
      %td= checkout.user_name
      %td= checkout.distributor.user_name
      -if checkout.distributor_check_in.present?
        %td= checkout.distributor_check_in.user_name
      -else
        %td Not checked in yet
      %td= checkout.title
      %td= checkout.checked_out_at.strftime('%B %d, %Y %l:%M %p')
      -if checkout.checked_in_at.present?
        %td= checkout.checked_in_at.strftime('%B %d, %Y %l:%M %p')
      -else
        %td Not checked in yet
      %td= checkout.due_date.strftime('%B %d, %Y %l:%M %p')

.text-center
  =will_paginate @checkouts

app/views/checkouts/show.html.haml
.page-header
  %h1
    Checkout for
    = @checkout.title

.row
  - if @checkout.book.google_book_data.img_small.present?
    %div
      %a{href: book_path(@checkout.book)}
        %img.center{src: @checkout.book.google_book_data.img_small, height: '250px;'}
  -else
    %a{href: book_path(@checkout.book)}
      .blank-thumbnail-large.center
.row
  %dl.dl-horizontal
    %dt Checked Out By
    %dd= @checkout.user_name
    %dt Distributor Check Out
    %dd= @checkout.distributor.user_name
    %dt Date Checked Out
    %dd= @checkout.checked_out_at.strftime('%B %d, %Y')
    %dt Distributor Checked In
    %dd
      - if @checkout.checked_in_at.nil?
        Not checked in yet.
      - else
        = @checkout.distributor_check_in.user_name
    %dt Date Checked In
    %dd
      - if @checkout.checked_in_at.nil?
        Not checked in yet.
      - else
        = @checkout.checked_in_at.strftime('%B %d, %Y')
    %dt Due Date
    %dd= @checkout.due_date.strftime('%B %d, %Y')